CREATE TABLE rebel (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	age INT NOT NULL,
	genre VARCHAR(50) NOT NULL,
	localization VARCHAR(255) NOT NULL,
	latitude DECIMAL(10, 8) NOT NULL,
	longitude DECIMAL(11, 8) NOT NULL
);
