CREATE TABLE item (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	points INT NOT NULL DEFAULT 0
);

CREATE TABLE inventory_item (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	amount INT NOT NULL,
	item_id BIGINT NOT NULL,
	rebel_id BIGINT NOT NULL,
	FOREIGN KEY (item_id) REFERENCES item(id),
	FOREIGN KEY (rebel_id) REFERENCES rebel(id)
);
